ALTER TABLE "agent_inbox_items" ADD COLUMN "schedule_occurrence_id" uuid;--> statement-breakpoint
ALTER TABLE "agent_inbox_items" ADD CONSTRAINT "agent_inbox_items_owner_schedule_occurrence_fk" FOREIGN KEY ("user_id", "schedule_occurrence_id") REFERENCES "job_discovery_schedule_occurrences"("user_id", "id");--> statement-breakpoint
CREATE UNIQUE INDEX "agent_inbox_items_schedule_occurrence_unique_idx" ON "agent_inbox_items" ("schedule_occurrence_id") WHERE "schedule_occurrence_id" is not null;--> statement-breakpoint
ALTER TABLE "agent_inbox_items" DROP CONSTRAINT "agent_inbox_items_kind_check";--> statement-breakpoint
ALTER TABLE "agent_inbox_items" DROP CONSTRAINT "agent_inbox_items_reason_check";--> statement-breakpoint
ALTER TABLE "agent_inbox_items" DROP CONSTRAINT "agent_inbox_items_kind_reason_pair_check";--> statement-breakpoint
ALTER TABLE "agent_inbox_items" DROP CONSTRAINT "agent_inbox_items_reference_combination_check";--> statement-breakpoint
ALTER TABLE "agent_inbox_items" ADD CONSTRAINT "agent_inbox_items_kind_check" CHECK ("kind" in ('run_failed', 'budget_exhausted', 'decision_required', 'source_attention', 'discovery_attention', 'candidate_fact', 'recommendation_list', 'recommendation_result', 'calibration_proposal', 'schedule_attention'));--> statement-breakpoint
ALTER TABLE "agent_inbox_items" ADD CONSTRAINT "agent_inbox_items_reason_check" CHECK ("reason_code" in ('AGENT_RUN_PAUSED', 'SOURCE_HEALTH_ATTENTION', 'DISCOVERY_ATTENTION', 'CANDIDATE_FACT_PENDING', 'RECOMMENDATION_LIST_PUBLISHED', 'NO_RECOMMENDATIONS_PUBLISHED', 'CALIBRATION_PROPOSAL_CREATED', 'SCHEDULE_RUN_PREFLIGHT_BLOCKED', 'AGENT_RUN_ADAPTER_RETRYABLE', 'AGENT_RUN_ADAPTER_FAILED', 'AGENT_RUN_CONTENT_STORAGE_FAILED', 'AGENT_RUN_PERSIST_FAILED', 'AGENT_RUN_BUDGET_EXCEEDED', 'AGENT_RUN_MODEL_RETRYABLE', 'AGENT_RUN_MODEL_AUTH_FAILED', 'AGENT_RUN_MODEL_POLICY_REJECTED', 'AGENT_RUN_MODEL_INVALID_RESPONSE'));--> statement-breakpoint
ALTER TABLE "agent_inbox_items" ADD CONSTRAINT "agent_inbox_items_kind_reason_pair_check" CHECK (("kind" = 'source_attention') = ("reason_code" = 'SOURCE_HEALTH_ATTENTION') and ("kind" = 'discovery_attention') = ("reason_code" = 'DISCOVERY_ATTENTION') and ("kind" = 'candidate_fact') = ("reason_code" = 'CANDIDATE_FACT_PENDING') and ("kind" = 'recommendation_list') = ("reason_code" = 'RECOMMENDATION_LIST_PUBLISHED') and ("kind" = 'recommendation_result') = ("reason_code" = 'NO_RECOMMENDATIONS_PUBLISHED') and ("kind" = 'calibration_proposal') = ("reason_code" = 'CALIBRATION_PROPOSAL_CREATED') and ("kind" = 'schedule_attention') = ("reason_code" = 'SCHEDULE_RUN_PREFLIGHT_BLOCKED'));--> statement-breakpoint
ALTER TABLE "agent_inbox_items" ADD CONSTRAINT "agent_inbox_items_reference_combination_check" CHECK (
  ("kind" in ('run_failed', 'budget_exhausted', 'decision_required', 'discovery_attention') and "run_id" is not null and "trigger_event_sequence" is not null and "schedule_occurrence_id" is null and "candidate_fact_id" is null and "watchlist_item_id" is null and "source_health_check_id" is null and "recommendation_list_id" is null and "recommendation_result_id" is null and "calibration_proposal_id" is null)
  or ("kind" = 'source_attention' and "run_id" is not null and "schedule_occurrence_id" is null and "watchlist_item_id" is not null and "source_health_check_id" is not null and "candidate_fact_id" is null and "recommendation_list_id" is null and "recommendation_result_id" is null and "calibration_proposal_id" is null)
  or ("kind" = 'candidate_fact' and "run_id" is null and "trigger_event_sequence" is null and "schedule_occurrence_id" is null and "candidate_fact_id" is not null and "watchlist_item_id" is null and "source_health_check_id" is null and "recommendation_list_id" is null and "recommendation_result_id" is null and "calibration_proposal_id" is null)
  or ("kind" = 'recommendation_list' and "run_id" is null and "trigger_event_sequence" is null and "schedule_occurrence_id" is null and "candidate_fact_id" is null and "watchlist_item_id" is null and "source_health_check_id" is null and "recommendation_list_id" is not null and "recommendation_result_id" is null and "calibration_proposal_id" is null)
  or ("kind" = 'recommendation_result' and "run_id" is null and "trigger_event_sequence" is null and "schedule_occurrence_id" is null and "candidate_fact_id" is null and "watchlist_item_id" is null and "source_health_check_id" is null and "recommendation_list_id" is null and "recommendation_result_id" is not null and "calibration_proposal_id" is null)
  or ("kind" = 'calibration_proposal' and "run_id" is null and "trigger_event_sequence" is null and "schedule_occurrence_id" is null and "candidate_fact_id" is null and "watchlist_item_id" is null and "source_health_check_id" is null and "recommendation_list_id" is null and "recommendation_result_id" is null and "calibration_proposal_id" is not null)
  or ("kind" = 'schedule_attention' and "run_id" is null and "trigger_event_sequence" is null and "schedule_occurrence_id" is not null and "candidate_fact_id" is null and "watchlist_item_id" is null and "source_health_check_id" is null and "recommendation_list_id" is null and "recommendation_result_id" is null and "calibration_proposal_id" is null)
);
