packages:
  - apps/*
  - packages/*
allowBuilds:
  '@scarf/scarf': false
  cpu-features: false
  'esbuild@0.18.20 || 0.25.4 || 0.28.2': true
  msgpackr-extract: false
  protobufjs: false
  ssh2: false
minimumReleaseAgeExclude:
  - bullmq@6.2.2
