import { afterEach, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ reviseCompanyWatchlistItem: vi.fn(), readSessionToken: vi.fn(), rethrow: vi.fn() }));
vi.mock("@/lib/server/api-client", () => ({ api: { reviseCompanyWatchlistItem: mocks.reviseCompanyWatchlistItem } }));
vi.mock("@/lib/server/session-cookie", () => ({ readSessionToken: mocks.readSessionToken }));
vi.mock("next/navigation", () => ({ unstable_rethrow: mocks.rethrow }));
import { POST } from "./route";
const targetId = "d194d0ce-fc7e-45db-9425-e8ff4eaf8c08";
const itemId = "87ccabf1-f5fe-430c-9129-df14e4789ec0";
const context = (item = itemId) => ({ params: Promise.resolve({ targetId, itemId: item }) });
const command = { expectedVersion: 1, canonicalCompanyName: "曙光云图", careersUrl: "https://careers.aurora.example/jobs", allowedDomains: ["careers.aurora.example"], sourceNote: "公开入口" };
const overview = { target: { targetId, targetVersion: 1, targetState: "active", roleFamily: "AI 应用工程" }, version: 2, items: [{ itemId, canonicalCompanyName: command.canonicalCompanyName, careersUrl: command.careersUrl, allowedDomains: command.allowedDomains, sourceNote: command.sourceNote, state: "enabled", position: 1 }] };
afterEach(() => vi.clearAllMocks());
it("验证动态 itemId 与编辑命令并安全透传 400", async () => {
  const invalid = await POST(new Request("http://localhost", { method: "POST", body: JSON.stringify(command) }), context("invalid"));
  expect(invalid.status).toBe(404);
  mocks.readSessionToken.mockResolvedValue("a".repeat(43)); mocks.reviseCompanyWatchlistItem.mockRejectedValue({ status: 400, message: "secret" });
  expect((await POST(new Request("http://localhost", { method: "POST", body: JSON.stringify(command) }), context())).status).toBe(400);
  mocks.reviseCompanyWatchlistItem.mockResolvedValue(overview);
  const response = await POST(new Request("http://localhost", { method: "POST", body: JSON.stringify(command) }), context());
  expect(response.status).toBe(201); expect(mocks.reviseCompanyWatchlistItem).toHaveBeenCalledWith("a".repeat(43), targetId, itemId, command);
});
